import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@components/navbar/navbar";
import AuthProvider from "../app/components/SessionProvider"; // 引入刚刚创建的 SessionProvider
import "./globals.css";
import '@styles/base/base.scss';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar></Navbar>
        <AuthProvider>{children}</AuthProvider>
        
      </body>
    </html>
  );
}
// 'use client'
// import { SessionProvider } from "next-auth/react";

// export default function RootLayout({ children }) {
//   return (
//     <SessionProvider>
//       {children}
//     </SessionProvider>
//   );
// }